apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.5
          ports:
            - containerPort: 80
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: simple-app-config
                  key: WELCOME_MSG
